# Generated by Django 5.1.7 on 2025-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gpschip_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpschip',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
