# Generated by Django 5.1.7 on 2025-03-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gpschip_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpschip',
            name='slug',
        ),
    ]
