# Generated by Django 5.1.7 on 2025-04-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpschip',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
