# Generated by Django 5.1.7 on 2025-05-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_categorie_elementpanier_panier_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('PERSONNE', 'Personne'), ('ENFANT', 'Enfant')], default='VOITURE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='elementpanier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='elementpanier',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='elementpanier',
            name='produit',
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='panier',
            old_name='date_creation',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='panier',
            old_name='date_modification',
            new_name='mis_a_jour_le',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='date_ajout',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='actif',
            new_name='en_stock',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock',
        ),
        migrations.AddField(
            model_name='produit',
            name='mis_a_jour_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='ElementPanier',
        ),
    ]
